Repository fungover/haze, pull requests merged in 2023-02, with the labels that each got.

#49 Dockerfile
  Dockerfile
Labels: feature

#44 27 concurrent connections v2
  pom.xml
  src/main/java/org/fungover/haze/Main.java
  src/test/java/org/fungover/haze/MainTest.java
Labels: feature

#67 15 setnx
  src/main/java/org/fungover/haze/HazeDatabase.java
  src/main/java/org/fungover/haze/Main.java
  src/test/java/org/fungover/haze/HazeDatabaseTest.java
Labels: feature

#82 Change version to 1.0.0 in pom.xml
  pom.xml
Labels: major

#57 19 auth
  pom.xml
  src/main/java/org/fungover/haze/Auth.java
  src/main/java/org/fungover/haze/Initialize.java
  src/main/java/org/fungover/haze/Main.java
  src/test/java/org/fungover/haze/AuthTest.java
  src/test/java/org/fungover/haze/InitializeTest.java
Labels: enhancement, feature, major, breakingchange

#151 Call hazeList from main and huge refactor
  src/main/java/org/fungover/haze/HazeList.java
  src/main/java/org/fungover/haze/Main.java
  src/test/java/org/fungover/haze/HazeListTest.java
  src/test/java/org/fungover/haze/MainTest.java
Labels: enhancement

#153 150 trying to start docker container fails
  Dockerfile
  pom.xml
Labels: bug

#155 19 auth
  src/main/java/org/fungover/haze/Main.java
Labels: bug
